mastercard:
  api:
    environment:
      base-path: https://sandbox.api.mastercard.com/carbon  # Refers to sandbox endpoint
    authentication:
      key-file: classpath:MCI-Green-Team-sandbox.p12 # Copy .p12 file in src/main/resources and set value as classpath:nameOfYourP12File.p12
      consumer-key: o9C_cWyOaRoR5xkfNKQJ_zw1jDfix2ccQqg-k_Os358f6ce3!be9feebb714b4053b0d4713868c85cd50000000000000000 # Copy the Consumer key from "Sandbox/Production Keys" section on your project page
      keystore-alias: keyalias  # Alias of your key. Default key alias for sandbox is keyalias
      keystore-password: keystorepassword # Password of your Keystore. Default keystore password for sandbox project is keystorepassword
    encryption:
      key-file: classpath:carbon-calculatorClientEnc1682606125.pem  #client-encryption.pem
      fingerprint: ed96672380215ce0dcb7b376c3435cbd6194553e172671b0ba87dc5a3bede2e7 #fingerprint

test:
  data:
    bin: 5425  # Update with your bin
    card-base-currency: USD